title: Formal Mathematics
description: A course on the formalization of mathematics, using Lean4.
theme: just-the-docs

url: https://formal-mathematics.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
